// This file is automatically generated and should be regenerated
// using the FlutterFire CLI: https://firebase.flutter.dev/docs/cli/
// Run: `flutterfire configure` to generate this file with your Firebase credentials

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // TODO: Get your Firebase project credentials from Firebase Console
    // and use flutterfire configure to generate this file automatically
    
    // For now, returning a placeholder that will cause an error
    // This ensures developers know they need to configure Firebase
    throw UnsupportedError(
      'DefaultFirebaseOptions has not been configured for this platform. '
      'Please run `flutterfire configure` to generate the required configuration.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9Dzy9XLGDOkrKJKLyiNt6R3b1ATjWL48',
    appId: '1:1012255770120:web:f0317d53d431870020f3bd',
    messagingSenderId: '1012255770120',
    projectId: 'flash-me-7a1a2',
    authDomain: 'flash-me-7a1a2.firebaseapp.com',
    storageBucket: 'flash-me-7a1a2.firebasestorage.app',
    measurementId: 'G-K74BZCDSZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXxsvHsPnDrQXrSidC6Z72CZ1qYKn52_I',
    appId: '1:1012255770120:android:88276a8d818e94d020f3bd',
    messagingSenderId: '1012255770120',
    projectId: 'flash-me-7a1a2',
    storageBucket: 'flash-me-7a1a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaDzOQrbFQb6kqPap0gw3OwpWxQISwEh0',
    appId: '1:1012255770120:ios:ee9041eaaaa4c21c20f3bd',
    messagingSenderId: '1012255770120',
    projectId: 'flash-me-7a1a2',
    storageBucket: 'flash-me-7a1a2.firebasestorage.app',
    iosClientId: '1012255770120-g06g1csvtkuiin3quhs4mqg0365t00vn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashMeTemp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaDzOQrbFQb6kqPap0gw3OwpWxQISwEh0',
    appId: '1:1012255770120:ios:ee9041eaaaa4c21c20f3bd',
    messagingSenderId: '1012255770120',
    projectId: 'flash-me-7a1a2',
    storageBucket: 'flash-me-7a1a2.firebasestorage.app',
    iosClientId: '1012255770120-g06g1csvtkuiin3quhs4mqg0365t00vn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashMeTemp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9Dzy9XLGDOkrKJKLyiNt6R3b1ATjWL48',
    appId: '1:1012255770120:web:0d60f98d6bbb665020f3bd',
    messagingSenderId: '1012255770120',
    projectId: 'flash-me-7a1a2',
    authDomain: 'flash-me-7a1a2.firebaseapp.com',
    storageBucket: 'flash-me-7a1a2.firebasestorage.app',
    measurementId: 'G-M0RZS04E1X',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'YOUR_LINUX_API_KEY',
    appId: 'YOUR_LINUX_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
  );
}