// This file is automatically generated and should be regenerated
// using the FlutterFire CLI: https://firebase.flutter.dev/docs/cli/
// Run: `flutterfire configure` to generate this file with your Firebase credentials

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9Dzy9XLGDOkrKJKLyiNt6R3b1ATjWL48',
    appId: '1:1012255770120:web:0d60f98d6bbb665020f3bd',
    messagingSenderId: '1012255770120',
    projectId: 'flash-me-7a1a2',
    authDomain: 'flash-me-7a1a2.firebaseapp.com',
    storageBucket: 'flash-me-7a1a2.firebasestorage.app',
    measurementId: 'G-M0RZS04E1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXxsvHsPnDrQXrSidC6Z72CZ1qYKn52_I',
    appId: '1:1012255770120:android:e59e1a011f585cc220f3bd',
    messagingSenderId: '1012255770120',
    projectId: 'flash-me-7a1a2',
    storageBucket: 'flash-me-7a1a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaDzOQrbFQb6kqPap0gw3OwpWxQISwEh0',
    appId: '1:1012255770120:ios:35b3767d4f9ca9a620f3bd',
    messagingSenderId: '1012255770120',
    projectId: 'flash-me-7a1a2',
    storageBucket: 'flash-me-7a1a2.firebasestorage.app',
    androidClientId: '1012255770120-fs666f5dju609gc9kcpivdennj33jm1f.apps.googleusercontent.com',
    iosClientId: '1012255770120-6mqr8upsgjsouge0cpbqlvpegni1ub72.apps.googleusercontent.com',
    iosBundleId: 'com.t33r.agora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaDzOQrbFQb6kqPap0gw3OwpWxQISwEh0',
    appId: '1:1012255770120:ios:35b3767d4f9ca9a620f3bd',
    messagingSenderId: '1012255770120',
    projectId: 'flash-me-7a1a2',
    storageBucket: 'flash-me-7a1a2.firebasestorage.app',
    androidClientId: '1012255770120-fs666f5dju609gc9kcpivdennj33jm1f.apps.googleusercontent.com',
    iosClientId: '1012255770120-6mqr8upsgjsouge0cpbqlvpegni1ub72.apps.googleusercontent.com',
    iosBundleId: 'com.t33r.agora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9Dzy9XLGDOkrKJKLyiNt6R3b1ATjWL48',
    appId: '1:1012255770120:web:d06cb6c0291fbca420f3bd',
    messagingSenderId: '1012255770120',
    projectId: 'flash-me-7a1a2',
    authDomain: 'flash-me-7a1a2.firebaseapp.com',
    storageBucket: 'flash-me-7a1a2.firebasestorage.app',
    measurementId: 'G-H43LKCT202',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'YOUR_LINUX_API_KEY',
    appId: 'YOUR_LINUX_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
  );
}