part of '../import_service.dart';

// ---------------------------------------------------------------------------
// Card parsing — raw ZIP JSON → ImportCardData.
// Handles both standard question maps and ##templateId references.
// ---------------------------------------------------------------------------

// Coerce an optional untrusted JSON value into a list of objects (#300 F3).
// A file can be valid JSON but the wrong shape (e.g. `"sets": "x"`), which a
// bare `as List` would surface as an unhandled TypeError. Validates eagerly so
// the returned `.cast()` can't fail later — `List.cast<T>()` is a lazy view in
// Dart, so an unchecked bad element throws during iteration, far from here.
List<Map<String, dynamic>> _asObjectList(dynamic value, String field) {
  if (value == null) return [];
  if (value is! List) {
    throw AppException('Invalid format: "$field" must be a list.');
  }
  for (var i = 0; i < value.length; i++) {
    if (value[i] is! Map<String, dynamic>) {
      throw AppException(
          'Invalid format: entry ${i + 1} of "$field" is not an object.');
    }
  }
  return value.cast<Map<String, dynamic>>();
}

// Parse a single raw card map from cards.json into an ImportCardData.
// Throws AppException for cards that are missing required fields.
ImportCardData _parseCard(
    Map<String, dynamic> raw, Map<String, QuestionTemplate> qtMap) {
  final word = raw['primaryWord'] as String? ?? '';
  final translation = raw['translation'] as String? ?? '';
  if (word.isEmpty) throw AppException('A card is missing primaryWord.');
  if (translation.isEmpty) {
    throw AppException('Card "$word" is missing translation.');
  }

  // Accept both 'questions' (new format) and 'fields' (legacy ZIP export).
  final rawFields = ((raw['questions'] ?? raw['fields']) as List? ?? [])
      .cast<Map<String, dynamic>>();

  // Validate and resolve each question entry.
  // Template references ("template": "##id") are expanded here so that all
  // downstream code (diff, build) sees standard question maps.
  final resolvedFields = <Map<String, dynamic>>[];
  for (final f in rawFields) {
    if (_isTemplateRef(f)) {
      // ##id reference — look up in the user's question templates.
      final refValue = f['template'] as String;
      final refId = refValue.substring(kTemplateIdPrefix.length);
      final qt = qtMap[refId];
      if (qt == null) {
        throw AppException(
          'Card "$word" references unknown question template '
          '"$refValue". Create this question template before importing.',
        );
      }
      resolvedFields.add(_resolveTemplateRef(qt, f));
    } else {
      // Standard question entry — name/prompt interchangeable; content required.
      if ((f['name'] == null && f['prompt'] == null) ||
          f['type'] == null ||
          f['content'] == null) {
        throw AppException('Card "$word" has a malformed question entry.');
      }
      resolvedFields.add(f);
    }
  }

  return ImportCardData(
    primaryWord: word,
    translation: translation,
    primaryWordHidden: raw['primaryWordHidden'] as bool? ?? false,
    mediaImagePath: raw['primaryImageUrl'] as String?,
    mediaAudioPath: raw['primaryAudioUrl'] as String?,
    rawFields: resolvedFields,
    templateId: raw['templateId'] as String?,
    tags: List<String>.from(raw['tags'] as List? ?? []),
  );
}

// Returns true when a raw question map is a ##templateId reference.
bool _isTemplateRef(Map<String, dynamic> f) {
  final t = f['template'];
  return t is String && t.startsWith(kTemplateIdPrefix);
}

// Expand a ##templateId reference into a standard question map by merging
// the template's question structure with any answer overrides in [ref].
Map<String, dynamic> _resolveTemplateRef(
    QuestionTemplate qt, Map<String, dynamic> ref) {
  final qJson = Map<String, dynamic>.from(qt.question.toJson());
  qJson.remove('questionId'); // fresh ID is generated by _buildQuestions

  // Merge answer-field overrides from the ref entry into the content map.
  final content =
      Map<String, dynamic>.from(qJson['content'] as Map<String, dynamic>? ?? {});
  for (final key in ['correctIndex', 'correctAnswers', 'correctOrder', 'wordBank']) {
    if (ref.containsKey(key)) content[key] = ref[key];
  }
  qJson['content'] = content;
  return qJson;
}

// Build a CardQuestion list from raw ZIP JSON maps, generating fresh IDs.
// Unknown types (e.g. legacy 'reveal') are silently skipped.
List<CardQuestion> _buildQuestions(List<Map<String, dynamic>> rawFields) {
  final questions = <CardQuestion>[];
  for (final f in rawFields) {
    try {
      questions.add(CardQuestion.fromJson({
        ...f,
        'questionId': CardQuestion.generateId(),
      }));
    } on ArgumentError {
      // skip unsupported types
    }
  }
  return questions;
}